apiVersion: v1
kind: Namespace
metadata:
  name: falco

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: falco
data:
  falco.yaml: |
    rules_file: /etc/falco/falco_rules.yaml
    syscalls_buffer_size: 32768
    log_stderr: true
  falco_rules.yaml: |
    - rule: Shell spawned in container
      desc: A shell (sh, bash, zsh) was spawned in a container
      condition: spawned_process and container and proc.name in (bash,sh,zsh,ash)
      output: Shell spawned in container (user=%user.name container=%container.name proc=%proc.name cmd=%proc.cmdline)
      priority: WARNING
      tags: [container, shell]

    - rule: Unexpected write to /etc
      desc: A process wrote to /etc inside a container (possible tamper)
      condition: evt.type = write and fd.name startswith /etc and container
      output: Write to /etc in container by %proc.name (container=%container.name user=%user.name cmd=%proc.cmdline)
      priority: NOTICE
      tags: [container, integrity]

    - rule: Privileged process in container
      desc: Unexpected setuid/setgid or capability changes
      condition: (evt.type in (setuid,setgid) or proc.cap_effective) and container
      output: Privilege change in container (proc=%proc.name cmd=%proc.cmdline)
      priority: CRITICAL
      tags: [container, privilege]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      serviceAccountName: falco-sa
      tolerations:
        - operator: Exists
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /host/dev
            - name: proc
              mountPath: /host/proc
            - name: boot
              mountPath: /boot
            - name: lib-modules
              mountPath: /lib/modules
            - name: etc-falco
              mountPath: /etc/falco
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: proc
          hostPath:
            path: /proc
        - name: boot
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: etc-falco
          configMap:
            name: falco-config
