apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: secure-ml-api
  namespace: secure-ml
  labels:
    app.kubernetes.io/name: secure-ml-api
    app.kubernetes.io/part-of: secure-ml
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  selector:
    matchLabels:
      app: secure-ml-api
  template:
    metadata:
      labels:
        app: secure-ml-api
    spec:
      containers:
        - name: api

          image: docker.io/REPLACE_AT_RUNTIME/secure-ml-api:latest
          imagePullPolicy: IfNotPresent


          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET


          ports:
            - name: http
              containerPort: 8000


          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3


          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
