name: DevSecOps Pipeline

permissions:
  actions: read
  contents: read
  security-events: write
  issues: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # -------------------- SAST --------------------
  codeql:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # -------------------- SCA / IaC --------------------
  trivy:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy on Docker image
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: 'secure-ml-api:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Run Trivy on Terraform IaC
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: 'fs'
          scan-ref: 'terraform-deployment'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

  # -------------------- DAST --------------------
  zap_scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start API in background
        run: |
          docker build -t secure-ml-api ./secure-ml-api
          docker run -d -p 8000:8000 secure-ml-api
          sleep 15  # give app time to start

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8000/docs'
          cmd_options: '-a'
          issue_title: "OWASP ZAP Baseline Report"
          fail_action: false

      - name: Upload ZAP Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_json.json
            report_md.md

  # -------------------- Docker Build & Push --------------------
  docker_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [codeql, trivy, zap_scan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/secure-ml-api:latest ./secure-ml-api

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/secure-ml-api:latest
