name: DevSecOps (Checkov + Terraform Plan EKS)

on:
  push:
    branches: [ main, part-2 ]
  pull_request:

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_VAR_aws: '{"region":"eu-west-2"}'
  TF_VAR_cluster_name: "secure-ml-eks"
  TF_VAR_vpc_cidr: "10.0.0.0/16"
  TF_VAR_tags: '{"Project":"secure-ml-api","Env":"dev"}'

jobs:
  checkov:
    name: Checkov Scan (Terraform)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform-eks
          quiet: true
          output_format: sarif
          output_file_path: results.sarif
          log_level: WARNING

  terraform-plan-eks:
    name: Terraform Plan (EKS)
    runs-on: ubuntu-latest
    needs: checkov
    # Using static AWS keys from repo secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform fmt (check)
        working-directory: terraform-eks
        run: terraform fmt -check -recursive

      - name: Terraform Init (non-interactive)
        working-directory: terraform-eks
        env:
          TF_INPUT: "false"
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform-eks
        run: terraform validate

      - name: Terraform Plan (non-interactive)
        working-directory: terraform-eks
        env:
          TF_INPUT: "false"
        run: terraform plan -input=false -out=tfplan.out
