name: DevSecOps Pipeline (EKS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  codeql:
    name: CodeQL (SAST)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3

  trivy:
    name: Trivy (Image + EKS IaC)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build image for scan
        run: docker build -t secure-ml-api:latest .
      - name: Trivy (Image) - fail on HIGH/CRITICAL
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: secure-ml-api:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
      - name: Trivy (Terraform IaC for EKS) - fail on HIGH/CRITICAL
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: fs
          scan-ref: terraform-eks
          format: table
          exit-code: 1
          ignore-unfixed: true

  checkov:
    name: Checkov (EKS Terraform policy)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform-eks
          soft_fail: false

  sbom:
    name: SBOM (Syft)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build image for SBOM
        run: docker build -t secure-ml-api:latest .
      - name: Generate SBOM (SPDX JSON)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/syft:latest packages docker:secure-ml-api:latest -o spdx-json > sbom.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

  terraform-plan:
    name: Terraform Plan (EKS) — review only
    runs-on: ubuntu-latest
    needs: [trivy, checkov, sbom]
    permissions:
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init (EKS)
        run: terraform -chdir=terraform-eks init
      - name: Terraform Plan (EKS)
        run: terraform -chdir=terraform-eks plan