name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeql-analysis:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v2
        with:
          languages: python
      - uses: github/codeql-action/analyze@v2

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image for Trivy scan
        run: docker build -t secure-ml-api:latest .
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: secure-ml-api:latest
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

  zap-baseline-scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create Docker network if testing locally
      - name: Create Docker Network
        run: docker network create zapnet || true

      # Start API container in background (replace this with your service build)
      - name: Start API Container
        run: |
          docker build -t myapi .
          docker run -d --name api --network zapnet -p 8000:8000 myapi

      # Run ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports

          docker run --rm \
            -v $(pwd)/zap-reports:/zap/wrk \
            --network zapnet \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://api:8000/docs \
              -J zap-report.json \
              -w zap-report.md \
              -r zap-report.html \
              -a || true

      - name: List generated ZAP reports
        run: ls -lah zap-reports

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: zap-reports/*
