name: Secure ML API CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v2
        with:
          languages: python
      - uses: github/codeql-action/analyze@v2

  dependency-review:
    name: Dependency Review (PR Gate)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create a cache dir for Trivy DB and cache it between runs
      - name: Prep Trivy cache dir
        run: mkdir -p ~/.cache/trivy

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db

      # Use Dockerized Trivy so we don't depend on installing a specific .deb
      - name: Run Trivy scan on docker image (Dockerized)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache/trivy:/root/.cache/ \
            aquasec/trivy:latest image \
              --format table \
              --output trivy-results.txt \
              --vuln-type os,library \
              --severity HIGH,CRITICAL \
              --timeout 10m \
              ${{ secrets.DOCKERHUB_USERNAME }}/secure-ml-api:latest

      - name: Upload Trivy Scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-results.txt

  terraform-plan:
    name: Terraform Plan (Review Only)
    runs-on: ubuntu-latest
    needs: [codeql, trivy-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Run Terraform from the folder that actually contains your .tf files
      - name: Terraform Init
        working-directory: ./terraform-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_allowed_cidr: ${{ secrets.ALLOWED_CIDR }}
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform-deployment/tfplan

  zap-scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: [trivy-scan]
    steps:
      - uses: actions/checkout@v4

      # Start your API container so ZAP has something real to hit
      - name: Start API container
        run: |
          docker run -d --name api -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/secure-ml-api:latest
          # wait until /docs returns HTTP 200 or 60s timeout
          for i in {1..60}; do
            if curl -fsS http://localhost:8000/docs >/dev/null; then
              echo "API is up"
              break
            fi
            sleep 1
          done

      - name: Create report directory
        run: mkdir -p zap-reports

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network=host \
            -v $(pwd)/zap-reports:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://localhost:8000 \
              -I \
              -r zap-report.html \
              -J zap-report.json \
              -w zap-report.md || true

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: zap-reports/*
